apiVersion: v1
kind: Service
metadata:
  name: api-service-loadbalancer
  namespace: public-sample-apps
spec:
  type: LoadBalancer
  selector:
    name: expensive-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
