# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
        server-id: github-anthonyikeda-expensive-api # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - id: build
      name: Build with Maven
      run: mvn -B package --file pom.xml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - id: java-setup
        name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - id: git-config
        name: Configure Git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - id: maven-release
        name: Release with Maven
        run: |
          ./mvnw release:prepare release:perform -B -s .maven_settings.xml
        env:
          CI_DEPLOY_USERNAME: ${GITHUB_ACTOR}
          CI_DEPLOY_PASSWORD: ${GITHUB_TOKEN}
      - id: rollback-if-failed
        name: Rollback in case the release failed
        if: steps.maven-release.outcome == 'failure'
        run: |
          ./mvnw release:rollback -B -s .maven_settings.xml
        env:
          CI_DEPLOY_USERNAME: ${GITHUB_ACTOR}
          CI_DEPLOY_PASSWORD: ${GITHUB_TOKEN}
